<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Siva-Praveen" ignored="3" name="Default test(failed)" tests="8" failures="2" timestamp="21 Jun 2022 14:18:44 GMT" time="0.29" errors="0">
  <testcase name="Tc4" time="0.03" classname="com.testNG.co.D">
    <skipped/>
  </testcase> <!-- Tc4 -->
  <testcase name="Tc4" time="0.004" classname="com.testNG.co.D">
    <skipped/>
  </testcase> <!-- Tc4 -->
  <testcase name="Tc4" time="0.011" classname="com.testNG.co.D">
    <skipped/>
  </testcase> <!-- Tc4 -->
  <testcase name="Tc4" time="0.005" classname="com.testNG.co.D">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testNG.co.D.Tc4(D.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Tc4 -->
  <testcase name="Tc2" time="0.005" classname="com.testNG.co.D">
    <skipped/>
  </testcase> <!-- Tc2 -->
  <testcase name="Tc2" time="0.013" classname="com.testNG.co.D">
    <skipped/>
  </testcase> <!-- Tc2 -->
  <testcase name="Tc2" time="0.005" classname="com.testNG.co.D">
    <skipped/>
  </testcase> <!-- Tc2 -->
  <testcase name="Tc2" time="0.007" classname="com.testNG.co.D">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testNG.co.D.Tc2(D.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Tc2 -->
  <testcase name="Tc5" time="0.0" classname="com.testNG.co.D">
    <ignored/>
  </testcase> <!-- Tc5 -->
  <testcase name="Tc3" time="0.0" classname="com.testNG.co.D">
    <ignored/>
  </testcase> <!-- Tc3 -->
  <testcase name="Tc1" time="0.0" classname="com.testNG.co.D">
    <ignored/>
  </testcase> <!-- Tc1 -->
</testsuite> <!-- Default test(failed) -->
